### ISSUE TITLE
Cannot find service 'setter.set'

### ISSUE THREAD

**Issue by danielbrunt57** [dlashua/hass-setter#1]
Running Home Assistant 0.117.4 and after adding this integration via HACS I do not see the service setter.set.  My log only has this one line containing "setter":
`2020-11-04 14:41:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for setter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`

Tks,
Daniel

**Comment by victorclaessen** [comment]
I have the same issue.

**Comment by dlashua** [comment]
This may be broke in 0.117.0? I'll test later today and see if I can resolve this.

**Comment by dlashua** [comment]
I tested with 0.117.5 and it works just fine.

You need to be sure you include the following in `configuration.yaml`:

```
setter: 
```

Since this isn't in the README now, I'll add it. Hopefully that resolves your issue.

**Comment by danielbrunt57** [comment]
Thanks, that was the problem!
